version: "3.9"

volumes:
  docker:
  pgadmin:

services:
  jmt-db:
    image: postgres
    container_name: jmt-db
    ports:
      - 5432:5432
    volumes:
      - docker:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass

  jmt-admin4:
    # host name: host.docker.internal
    image: dpage/pgadmin4
    container_name: jmt-pgadmin
    ports:
      - 80:80
    volumes:
      - pgadmin:/var/lib/pgadmin4
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=pass

  jmt-server:
    image: tomcat:9.0.56-jre11-openjdk
    container_name: jmt-tomcat-server
    ports:
      - 8080:8080
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    entrypoint:
      - catalina.sh
      - run